import type { CSSProperties } from "react";

export const s = {
  body: { display: "grid", gridTemplateColumns: "minmax(0, 1.1fr) minmax(0, 1fr)", minHeight: 440 } satisfies CSSProperties,
  left: { padding: "16px 20px", borderRight: "1px solid var(--border)", minWidth: 0, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  right: { padding: "16px 20px", minWidth: 0, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  required: { color: "var(--crit)" } satisfies CSSProperties,
  input: { width: "100%", padding: "9px 12px", fontSize: 14, borderRadius: 8, border: "1px solid var(--border-strong)", background: "var(--bg-surface)", color: "var(--text-primary)", boxSizing: "border-box" } satisfies CSSProperties,
  textarea: { width: "100%", flex: 1, minHeight: 260, padding: 12, fontSize: 12.5, lineHeight: 1.5, borderRadius: 8, border: "1px solid var(--border)", background: "var(--code-bg)", color: "var(--text-primary)", resize: "vertical", boxSizing: "border-box" } satisfies CSSProperties,
  tabs: { display: "flex", gap: 4, borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  tab: (active: boolean): CSSProperties => ({
    padding: "8px 14px",
    fontSize: 14,
    fontWeight: active ? 600 : 500,
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    background: "transparent",
    border: "none",
    borderBottom: `2px solid ${active ? "var(--accent)" : "transparent"}`,
    cursor: "pointer",
  }),
  fields: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 } satisfies CSSProperties,
  full: { gridColumn: "1 / -1" } satisfies CSSProperties,
  fieldLabel: { fontSize: 12, color: "var(--text-muted)", marginBottom: 4, display: "block" } satisfies CSSProperties,
  rightHead: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  valid: (ok: boolean): CSSProperties => ({
    fontSize: 12.5,
    fontWeight: 600,
    padding: "3px 10px",
    borderRadius: 6,
    background: ok ? "var(--ok-bg)" : "var(--crit-bg)",
    color: ok ? "var(--ok)" : "var(--crit)",
  }),
  errors: { margin: 0, paddingLeft: 18, fontSize: 12.5, color: "var(--crit)", display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  banner: (status: string): CSSProperties => ({
    marginTop: "auto",
    padding: "10px 14px",
    borderRadius: 8,
    fontSize: 13,
    border: `1px solid ${status === "passed" ? "var(--ok)" : status === "failed" ? "var(--crit)" : "var(--warn)"}`,
    background: status === "passed" ? "var(--ok-bg)" : status === "failed" ? "var(--crit-bg)" : "var(--warn-bg)",
  }),
  serverError: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  runOnSave: { display: "flex", alignItems: "center", gap: 8, fontSize: 14, color: "var(--text-secondary)", marginRight: "auto" } satisfies CSSProperties,
  fileList: { margin: 0, paddingLeft: 18, fontSize: 13 } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
};
