import type { CSSProperties } from "react";

export const s = {
  page: { display: "flex", height: "100%", minHeight: 0 } satisfies CSSProperties,
  left: {
    width: 300,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    borderRight: "1px solid var(--border-subtle)",
    background: "var(--bg-surface, transparent)",
  } satisfies CSSProperties,
  leftHeader: { padding: "16px 16px 8px" } satisfies CSSProperties,
  smallCaps: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  rootsLine: { marginTop: 4, fontSize: 11.5, color: "var(--text-secondary)", overflowWrap: "anywhere" } satisfies CSSProperties,
  toolbar: { display: "flex", alignItems: "center", gap: 4, padding: "0 12px 8px" } satisfies CSSProperties,
  iconButton: {
    width: 30,
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  iconButtonActive: { background: "var(--bg-hover)", color: "var(--text-primary)" } satisfies CSSProperties,
  spin: { animation: "ddspin 0.9s linear infinite" } satisfies CSSProperties,
  rootsEditorBand: { padding: "0 16px 12px", borderBottom: "1px solid var(--border-subtle)" } satisfies CSSProperties,
  listScroll: { flex: 1, minHeight: 0, overflowY: "auto", padding: "4px 8px" } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  rowButton: {
    width: "100%",
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    border: "none",
    borderLeft: "3px solid transparent",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  rowButtonActive: {
    background: "var(--accent-bg)",
    borderLeft: "3px solid var(--accent)",
  } satisfies CSSProperties,
  rowIcon: { flexShrink: 0, marginTop: 2, color: "var(--text-muted)" } satisfies CSSProperties,
  rowPath: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 1, lineHeight: 1.35 } satisfies CSSProperties,
  rowDir: { fontSize: 10.5, color: "var(--text-muted)", overflowWrap: "anywhere" } satisfies CSSProperties,
  rowBase: { fontWeight: 600, overflowWrap: "anywhere" } satisfies CSSProperties,
  rowTag: {
    flexShrink: 0,
    marginTop: 2,
    fontSize: 9.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    padding: "1px 6px",
    borderRadius: 4,
  } satisfies CSSProperties,
  leftBand: { padding: "8px 12px" } satisfies CSSProperties,
  footer: {
    flexShrink: 0,
    padding: "10px 16px",
    borderTop: "1px solid var(--border-subtle)",
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  right: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", minHeight: 0 } satisfies CSSProperties,
  rightHeader: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 24px",
    borderBottom: "1px solid var(--border-subtle)",
    minHeight: 49,
  } satisfies CSSProperties,
  headerPath: { fontSize: 13, fontWeight: 600, overflowWrap: "anywhere", minWidth: 0 } satisfies CSSProperties,
  headerDir: { color: "var(--text-muted)" } satisfies CSSProperties,
  tabs: {
    flexShrink: 0,
    display: "inline-flex",
    padding: 2,
    borderRadius: 7,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  tab: {
    padding: "3px 12px",
    borderRadius: 5,
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  tabActive: { background: "var(--bg-elevated)", color: "var(--text-primary)", fontWeight: 600 } satisfies CSSProperties,
  confirmBody: { margin: 0, fontSize: 14, color: "var(--text-secondary)" } satisfies CSSProperties,
  confirmFooter: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
  usedBy: {
    marginLeft: "auto",
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  rightScroll: { flex: 1, minHeight: 0, overflowY: "auto", padding: "20px 32px 32px" } satisfies CSSProperties,
  rightBand: { padding: "24px 32px" } satisfies CSSProperties,
};
