import type { CSSProperties } from "react";

/** Co-located styles for StatsTab. */
export const s = {
  root: { display: "flex", flexDirection: "column", gap: 20, padding: 20 } satisfies CSSProperties,
  tiles: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 12 } satisfies CSSProperties,
  tile: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: 18,
    minHeight: 104,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  tileHead: { display: "flex", alignItems: "center", justifyContent: "space-between" } satisfies CSSProperties,
  tileLabel: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  tileValue: { fontSize: 30, fontWeight: 700, letterSpacing: "-0.02em", marginTop: 12 } satisfies CSSProperties,
  tileUnit: { fontSize: 16, fontWeight: 500, color: "var(--text-muted)" } satisfies CSSProperties,
  ringText: { fontSize: 10, fontWeight: 600, fill: "var(--text-primary)" } satisfies CSSProperties,
  panels: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 12 } satisfies CSSProperties,
  panel: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: 18,
  } satisfies CSSProperties,
  panelHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    color: "var(--text-muted)",
    fontSize: 11.5,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  agentList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    fontSize: 13.5,
  } satisfies CSSProperties,
  agentIcon: {
    display: "inline-flex",
    padding: 5,
    borderRadius: 6,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  agentName: { flex: 1, fontWeight: 500 } satisfies CSSProperties,
  state: (enabled: boolean): CSSProperties => ({
    fontSize: 12,
    color: enabled ? "var(--ok)" : "var(--text-muted)",
  }),
  caveat: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5, margin: 0 } satisfies CSSProperties,
  muted: { color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,
} as const;
