import type { CSSProperties } from "react";

export const s = {
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  item: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    paddingBottom: 12,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  symbolRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap",
    width: "100%",
    border: "none",
    background: "none",
    padding: 0,
    margin: 0,
    font: "inherit",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  chevron: { flexShrink: 0, color: "var(--text-muted)" } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  symbolName: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  symbolFile: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  count: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  callerList: {
    listStyle: "none",
    margin: 0,
    padding: "0 0 0 4px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  callerItem: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontSize: 13,
  } satisfies CSSProperties,
  callerLink: { fontSize: 13 } satisfies CSSProperties,
  callerText: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  callerName: { color: "var(--text-muted)" } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 4, marginTop: 4 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  factItem: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
