import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    marginBottom: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  title: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  usage: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  summary: { margin: 0, fontSize: 14, lineHeight: 1.55, color: "var(--text-primary)", whiteSpace: "pre-wrap" } satisfies CSSProperties,
  stack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 14,
    alignItems: "start",
  } satisfies CSSProperties,
  column: { display: "flex", flexDirection: "column", gap: 14, minWidth: 0 } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  sectionHead: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  muted: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    padding: "8px 12px",
    fontSize: 13,
    borderRadius: 6,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  errorBanner: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "10px 12px",
    fontSize: 13,
    borderRadius: 6,
    color: "var(--text-primary)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  errorTitle: { fontWeight: 600 } satisfies CSSProperties,
  errorActions: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  link: { color: "var(--accent-text)", textDecoration: "underline" } satisfies CSSProperties,
  riskRow: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "stretch",
    maxWidth: "100%",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  riskTop: { display: "flex", alignItems: "stretch", minWidth: 0 } satisfies CSSProperties,
  riskMain: { display: "flex", flexDirection: "column", gap: 4, padding: "8px 12px", minWidth: 0 } satisfies CSSProperties,
  riskTitleRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  riskSeverity: { whiteSpace: "nowrap", fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.04em" } satisfies CSSProperties,
  riskToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    padding: "0 10px",
    background: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--border)",
    cursor: "pointer",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskExplanation: { margin: 0, padding: "0 12px 10px", fontSize: 13, lineHeight: 1.5, color: "var(--text-secondary)", whiteSpace: "pre-wrap" } satisfies CSSProperties,
  refs: { display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center", minWidth: 0 } satisfies CSSProperties,
  refButton: {
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "var(--accent-text)",
    fontSize: 13,
    textAlign: "left",
    fontFamily: "var(--font-mono, monospace)",
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  refNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  focusCard: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: "14px 16px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg)",
  } satisfies CSSProperties,
  focusList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  focusItem: { display: "flex", gap: 8, alignItems: "baseline", fontSize: 13, minWidth: 0 } satisfies CSSProperties,
  focusBullet: { color: "var(--text-muted)", flexShrink: 0, alignSelf: "center" } satisfies CSSProperties,
  focusText: { display: "flex", flexWrap: "wrap", gap: 6, alignItems: "baseline", minWidth: 0 } satisfies CSSProperties,
  headIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  focusReason: { color: "var(--text-secondary)" } satisfies CSSProperties,
  empty: { display: "flex", flexDirection: "column", gap: 8, alignItems: "flex-start" } satisfies CSSProperties,
};
