import type { CSSProperties } from "react";

export const s = {
  stack: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  heading: { margin: 0, fontSize: 16, fontWeight: 600, outline: "none" } satisfies CSSProperties,
  toggle: {
    display: "inline-flex",
    alignItems: "center",
    background: "transparent",
    border: "none",
    padding: 4,
    cursor: "pointer",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  body: { marginTop: 12, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  mono: { fontFamily: "var(--font-mono, monospace)", fontSize: 13 } satisfies CSSProperties,
  dim: { color: "var(--text-tertiary)", fontSize: 12 } satisfies CSSProperties,
  note: {
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,
  subhead: { margin: 0, fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  command: {
    flex: 1,
    minWidth: 0,
    padding: "4px 8px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  iconButton: {
    display: "inline-flex",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: 4,
    cursor: "pointer",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  link: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "var(--accent, var(--text-secondary))",
  } satisfies CSSProperties,
} as const;
